[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "labeling"
version = "0.1.0"
description = "A Python package for labeling data"

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^1.0.0"
